### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by bennycode** [vigour-io/is-number-like#4]
Using `const isNumber = require('lodash.isfinite')` in combination with `'use strict'` in [index.js](https://github.com/vigour-io/is-number-like/blob/master/lib/index.js) breaks compatibility with Node.js v0.12.

My build fails because of that:

> /home/travis/build/caiogondim/logdown.js/node_modules/browser-sync/node_modules/portscanner/node_modules/is-number-like/lib/index.js:2
const isNumber = require('lodash.isfinite')
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/travis/build/caiogondim/logdown.js/node_modules/browser-sync/node_modules/portscanner/lib/portscanner.js:4:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

Log: https://travis-ci.org/caiogondim/logdown.js/jobs/183316473

The result is that our logger module [logdown.js](https://github.com/caiogondim/logdown.js) is not compatible with Node.js v0.12 and below anymore. 😢

**Comment by jimdebeer** [comment]
hey i think it should work again, patched to use es5 again, use v 1.0.5
